/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 illust.gltf --transform
Author: anastasiaremezova (https://sketchfab.com/anastasiaremezova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/girl-portrait-192f257df39744009272310cf1a89f47
Title: Girl Portrait
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/illust-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_1.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_2.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_3.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_4.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_5.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_6.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_7.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_8.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_9.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_10.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_11.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_12.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_13.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Recovered_Tool_Recovered_Tool_0_14.geometry} material={materials.Recovered_Tool} />
        <mesh geometry={nodes.Extract3_Extract3_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract1_Extract1_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract7_Extract7_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract3_copy1_Extract3_copy1_0.geometry} material={materials.Extract3_copy1} />
        <mesh geometry={nodes.Extract3_copy1_Extract3_copy1_0_1.geometry} material={materials.Extract3_copy1} />
        <mesh geometry={nodes.Extract3_copy1_Extract3_copy1_0_2.geometry} material={materials.Extract3_copy1} />
        <mesh geometry={nodes.Extract2_Extract2_0.geometry} material={materials.Extract2} />
        <mesh geometry={nodes.Extract3_1_Extract3_1_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract14_Extract14_0.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_1.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_2.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_3.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_4.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_5.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_6.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_7.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_8.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_9.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_10.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_11.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract14_Extract14_0_12.geometry} material={materials.Extract14} />
        <mesh geometry={nodes.Extract15_Extract15_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract16_01_Extract16_01_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract16_Extract16_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract17_01_Extract17_01_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract17_Extract17_0.geometry} material={materials.Extract17} />
        <mesh geometry={nodes.Extract11_05_Extract11_05_0.geometry} material={materials.Extract11_05} />
        <mesh geometry={nodes.Extract11_06_Extract11_06_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract11_01_Extract11_01_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract11_02_Extract11_02_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract11_03_Extract11_03_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract11_Extract11_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract12_Extract12_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.Extract3_copy2_Extract3_copy2_0.geometry} material={materials.Extract3_copy2} />
        <mesh geometry={nodes.PM3D_Ring3D1_PM3D_Ring3D1_0.geometry} material={materials.PM3D_Ring3D1} />
        <mesh geometry={nodes.PM3D_Sphere3D1_1_PM3D_Sphere3D1_1_0.geometry} material={materials.Extract3} />
        <mesh geometry={nodes.PM3D_Sphere3D1_1_copy1_PM3D_Sphere3D1_1_copy1_0.geometry} material={materials.Extract3} />
      </group>
    </group>
  )
}

useGLTF.preload('/illust-transformed.glb')
